### ISSUE TITLE
Improve the documentation for Okta example

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam-documentation#112]
Article that needs to be updated: https://docs.ockam.io/guides/examples/okta

-- 

In the code example in [Engineer in San Francisco](https://docs.ockam.io/guides/examples/okta#engineer-for-san-francisco), replace:
- `ockam project import project.json` with:
- `ockam project import --project-file project.json`

-- 

Replace the 1st paragraph in [Required Dependencies](https://docs.ockam.io/guides/examples/okta#required-dependencies):

Through this example `https://trial-9434859.okta.com/oauth2/default` refers to an existing Okta endpoint where workforce identities are defined. Please create a trial account for Okta, if you don't have an account already. You can get your Okta URL and Client ID information from okta.com.

> If you create a trial account, make sure to create a new app integration for this example. Then choose "OIDC - OpenID connect" for the Sign-in method and "Native Application" for the Application type, in Okta's website.

--

To make it clearer that the okta.com URLs and Client IDs are placeholders, perhaps use all caps variable names in the code example below, in [Administrator](https://docs.ockam.io/guides/examples/okta#administrator) section:
- replace https://trial-9434859.okta.com/oauth2/default with YOUR_OKTA_OAUTH2_URL 
- and 0oa2pi8no6Kb04frP697 with YOUR_CLIENT_ID

**Comment by metaclips** [comment]
![Screenshot 2024-01-18 at 7 47 28 PM](https://github.com/build-trust/ockam-documentation/assets/31141573/56638000-71b8-41d8-9897-4a53cd3b9dce)
It's not specified what grant type is required to setup an OIDC application to use with `ockam project addon`

**Comment by nazmulidris** [comment]
Related issue: https://github.com/build-trust/ockam-documentation/pull/89
